
import os

import numpy as np

import radar_common as rc
import radar_golden as g

OUT_DIR = "vectors"
L = 2048
cfg = g.Cfg()


def write_hex(name, arr, bits, signed=True):
    mask = (1 << bits) - 1
    digits = (bits + 3) // 4
    with open(os.path.join(OUT_DIR, name), "w") as f:
        for v in np.asarray(arr).ravel():
            f.write(f"{int(v) & mask:0{digits}x}\n")


os.makedirs(OUT_DIR, exist_ok=True)

# ---------------------------------------------------------------- ROMs + params
twr, twi = g.twiddles(cfg)
ci, cq = rc.chirp_int()
hr, hi, k = g.make_reference(ci, cq, cfg)
write_hex("tw_re.hex", twr, cfg.tw_bits)
write_hex("tw_im.hex", twi, cfg.tw_bits)
write_hex("ref_re.hex", hr, cfg.ref_bits)
write_hex("ref_im.hex", hi, cfg.ref_bits)

_, _, alpha_q = g.cfar_fixed(np.zeros((1, L), dtype=np.int64), cfg)
with open(os.path.join(OUT_DIR, "radar_params.svh"), "w") as f:
    f.write("// Generated by radar_make_vectors.py. Do not edit by hand.\n")
    f.write("`ifndef RADAR_PARAMS_SVH\n`define RADAR_PARAMS_SVH\n")
    f.write(f"localparam int IN_BITS     = {cfg.in_bits};\n")
    f.write(f"localparam int DATA_BITS   = {cfg.data_bits};\n")
    f.write(f"localparam int TW_BITS     = {cfg.tw_bits};\n")
    f.write(f"localparam int REF_BITS    = {cfg.ref_bits};\n")
    f.write(f"localparam int N_FFT       = {rc.N_FFT};\n")
    f.write(f"localparam int PULSE_LEN   = {rc.PULSE_LEN};\n")
    f.write(f"localparam int HOP         = {rc.HOP};\n")
    f.write(f"localparam int FWD_SHIFTS [0:7] = '{{{', '.join(map(str, cfg.fwd_shifts))}}};\n")
    f.write(f"localparam int INV_SHIFTS [0:7] = '{{{', '.join(map(str, cfg.inv_shifts))}}};\n")
    f.write(f"localparam int REF_K       = {k};   // reference spectrum stored divided by 2^REF_K\n")
    f.write(f"localparam int MAG2_SHIFT  = {cfg.mag2_sh};\n")
    f.write(f"localparam int GUARD       = {cfg.guard};\n")
    f.write(f"localparam int TRAIN       = {cfg.train};   // per side\n")
    f.write(f"localparam int ALPHA_FRAC  = {cfg.alpha_frac};\n")
    f.write(f"localparam int ALPHA_Q     = {alpha_q};   // threshold = (sum_of_training_cells * ALPHA_Q) >>> ALPHA_FRAC\n")
    f.write(f"localparam int PEAK_HALF   = {cfg.peak_half};\n")
    f.write(f"localparam int STREAM_LEN  = {L};\n")
    f.write(f"localparam int VALID_LEN   = {rc.valid_len(L)};   // compare outputs only below this index\n")
    f.write("`endif\n")

# ---------------------------------------------------------------- test scenarios
# (name, description, kwargs for make_streams)
scenarios = [
    ("baseline_2a",  "the stream from radar_2a.py (-5 dB, echo at 700)", None),
    ("noise_only",   "noise only, no target (false-alarm check)",        dict(with_target=False)),
    ("block_edge",   "echo starts exactly on an overlap-save block edge (pos 256)", dict(target_pos=256)),
    ("straddle",     "echo straddles two blocks (pos 250)",              dict(target_pos=250)),
    ("near_start",   "echo near the start of the stream (pos 20)",       dict(target_pos=20)),
    ("near_end",     "echo at the last position the CFAR can evaluate", dict(target_pos=rc.valid_len(L) - 1 - rc.GUARD - rc.TRAIN)),
    ("blind_zone",   "echo inside the CFAR edge blind zone (pos 5): NOT reported is the expected behavior", dict(target_pos=5)),
    ("strong",       "strong echo (+10 dB SNR)",                         dict(snr_db=10.0)),
    ("weak",         "weak echo (-11 dB SNR, may be missed: that is expected behavior)", dict(snr_db=-11.0)),
    ("overflow",     "input scaled x4 to force internal saturation",     dict(snr_db=0.0, gain=4.0)),
]
n_random = 6
for r in range(n_random):
    scenarios.append((f"random{r}", "random position, random SNR in [-10, 0] dB", "random"))

manifest = []
for t, (name, desc, kw) in enumerate(scenarios):
    tag = f"t{t:02d}"
    if kw is None:
        d = np.load("radar_stream.npz")
        ii, qq = d["stream_i"].astype(np.int64)[None, :], d["stream_q"].astype(np.int64)[None, :]
        pos = np.array([int(d["target_pos"])])
        with_target = True
    else:
        if kw == "random":
            rng = np.random.default_rng(500 + t)
            kw = dict(snr_db=float(rng.uniform(-10, 0)))
        with_target = kw.get("with_target", True)
        z, pos = rc.make_streams(1, length=L, seed=1000 + t, **kw)
        ii, qq = rc.quantize(z)

    res = g.run_pipeline(ii, qq, ci, cq, cfg)
    mag2 = res["mag2"][0]
    width_m = max(int(mag2.max()).bit_length(), 1)
    write_hex(f"{tag}_in_i.hex", ii, cfg.in_bits)
    write_hex(f"{tag}_in_q.hex", qq, cfg.in_bits)
    write_hex(f"{tag}_exp_i.hex", res["out_i"], cfg.data_bits)
    write_hex(f"{tag}_exp_q.hex", res["out_q"], cfg.data_bits)
    write_hex(f"{tag}_exp_mag2.hex", mag2, width_m)
    write_hex(f"{tag}_exp_flag.hex", res["flags"][0].astype(int), 1)
    write_hex(f"{tag}_exp_report.hex", res["reports"][0].astype(int), 1)

    reports = np.flatnonzero(res["reports"][0]).tolist()
    tgt = int(pos[0]) if with_target else "none"
    manifest.append(f"{tag} {name}: {desc}\n     target {tgt}, expected reports {reports}, "
                    f"saturation events {res['info']['sat']}, mag2 width {width_m} bits")

with open(os.path.join(OUT_DIR, "manifest.txt"), "w") as f:
    f.write(f"stream length {L}, compare samples 0..{rc.valid_len(L) - 1}\n\n")
    f.write("\n".join(manifest) + "\n")

print(f"wrote {len(scenarios)} tests + ROMs + radar_params.svh to ./{OUT_DIR}/")
print(f"reference spectrum scale: 2^-{k}   alpha_q: {alpha_q}")
print()
print("\n".join(manifest))
